"""add phone and birth_date to players

Revision ID: ee22b2c1b036
Revises: 04409e68d859
Create Date: 2026-05-04 12:31:53.012393

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee22b2c1b036"
down_revision: str | Sequence[str] | None = "04409e68d859"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("phone", sa.String(length=20), nullable=True))
    op.add_column("players", sa.Column("birth_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "birth_date")
    op.drop_column("players", "phone")
    # ### end Alembic commands ###
